Feature/step2
orcohen5/or-cohen-evolution pull request #1
Opened 2020-03-17 16:48 UTC by orcohen5

2020-03-18 12:16 UTC, talrubin1123 requested changes
נשב נדבר נלמד ונתפתח :)

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Utilities/ExecutorServiceUtil.java
> +    private static final int THREADS_NUMBER = 5;
למה דווקא 5?

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Utilities/ExecutorServiceUtil.java
> +    private static ScheduledExecutorService startExecutor = Executors.newSingleThreadScheduledExecutor();
למה להשתמש ב scheduled?

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Events/EvolutionManager.java
> +    private List<Organism> americanOrganismsList;
למה יצרת משתנים מחלקתיים לערכים הספציפיים האלה?

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Events/EvolutionManager.java
>          planet = Planet.getInstance(continentsList);
instantiation will always be parameter-less. Otherwise your singleton is not a singleton.
תחשוב על זה

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Events/EvolutionManager.java
*אני יודעת ששמתי את התגובה במקום לא קשור, לא ידעתי איפה לשים*

שמות ה packages שלך לא נכונים. תחשוב על המשמעות של כל מחלקה ועל התפקיד שלה בפרויקט, תחלק מחדש לקבוצות ותחליף את החבילות.
אם אתה צריך עזרה אתה מוזמן ליצור קשר.
בכל מקרה מומלץ ללכת לחפש באינטרנט אחר סטנדרט חלוקה לחבילות בג'אווה

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +            Thread.sleep(1000);
למה?

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
>              executor.execute(organisms.get(i));
לא יודעת כמה זה קריא...

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
>          startOrganismsFight();
אם כבר אז Fights

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +            LoggerUtil.logData(continentData + fightData);
לדעתי יש פה בעיית אינקפסולציה. יש תלות בין ההדפסות של הקרבות לבין הדפסה כללית? זה לא יכול להיות

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +        List<Organism> attackersToRemove = new ArrayList();
למה שתי רשימות?

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +                        attacker.setOrganismAlive(false);
האם יש פה במקרה יתירות של אותו הדבר?

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +                        announceDraw(attacker, defender);
למה תיקו? במקרה הזה המותקף ניצח!

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +                    else {
ירידת שורה מיותר בין סגירת הבלוק של התנאי, ל-else

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +                    currentAttackers.remove(attacker);
לא מבינה למה השימוש בשתי הרשימות האלה. אשמח להסבר

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +                areAttackerAndDefenderHavePeople(attacker, defender);
שוב, האם יש פה יתירות?

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
*שוב סליחה שאני מעירה הערה כללית לא תחת שורה רלוונטית*

אז מימשת בעצמך את הסינכרון והזמינות של שבטים לקרב. זה יפה ודקדקני אבל לא הייתה זו המטרה. תחקור בבקשה על עקרונות הסינכרון בנושא ת'רדים. נדבר על זה בסקק החי.

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +    private final int DIFFERENCE = 5;
שם לא קריא

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +    private final int MINIMUM_BALANCE = 1;
לשם מה?

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +                    defender.setOrganismAlive(false);
בהמשך לתגובה של התיקו....

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +    private void announceFight(Organism attacker, Organism defender) {
לדעתי מיותר להכריז גם על התחלת קרב וגם על התוצאות שלו בשתי הדפסות נפרדות. הרי מה שאתה עושה זה כותב את אותו המידע פעמיים וגורם לזיבול רב של הלוגים שלך.

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Planet.java
>      public static Planet getInstance(List<Continent> continents) {
שורת הרווח מתחת מיותרת

בנוסף, שורות  רווח מגיעות לפני return תמיד,
ואחרי סגירת בלוק תמיד

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Planet.java
> +    private synchronized void startLifeCycle() {
האם צריך לעשות את הסבבים סינכרוניים?

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Places/Planet.java
> +            LoggerUtil.logData("______________");
או שפשוט תדפיס בסוף כל סבב?

2020-03-18 12:16 UTC, talrubin1123 commented on src/main/java/Utilities/ExecutorServiceUtil.java
> +    private static ScheduledExecutorService startExecutor = Executors.newSingleThreadScheduledExecutor();
ולמה לקרוא לזה ככה?

2020-03-18 13:58 UTC, orcohen5 commented on src/main/java/Events/EvolutionManager.java
> +    private List<Organism> americanOrganismsList;
היבשות אולי יכולות להיות משתנים לוקליים אך הרשימות צריכות להיות משתני מחלקה כדי שנוכל להפריד בין אתחול הרשימה כרשימה ריקה בקונסטרקטור ואז להוסיף ערכים לאותה רשימה בפונקציה אחרת כפי שנתבקשתי מנדב ויהודה באחד מסקרי הקוד הקודמים.

2020-03-18 14:05 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +            Thread.sleep(1000);
בתחילת ההרצה נדרש לתת לthread זמן כדי שלא תתבצע העלאה נוספת של האורגניזמים תוך כדי קרבות כפי שהיה לפני שהוספתי את השורה הזאת.
היה מצב שבו אורגניזם מודפס עם balance מסויים בהתחלה ואז מתחיל את הקרב עם balance גדול יותר (של המחזור הבא). כדי למנוע העלאה כפולה במקרה שביצוע קרבות לוקח קצת יותר זמן הוספתי את השורה הזו ואז כל הקרבות בוצעו עם balance תקין ולא הייתה העלאה שלא נדרשת.

2020-03-18 14:08 UTC, talrubin1123 commented on src/main/java/Events/EvolutionManager.java
> +    private List<Organism> americanOrganismsList;
אני מצטערת אבל זה לא נכון במקרה הזה. יכול להיות שנתבקשת לאתחל באופן כללי רשימות כשהן משתנה מחלקתי בקונסטרקטור. במקרה הזה הרשימות האלה הן לא חלק ממהות המחלקה. זאת אומרת, נניח והיית יוצר מופע של המחלקה, הייתה לך גישה גם לרשימות האלה כאילו הן תכונות של המחלקה

2020-03-18 14:11 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +            LoggerUtil.logData(continentData + fightData);
בפלט של התרגיל הדפסות הקרב מופיעות תוך כדי ההדפסות הרגילות בצורה אסינכרונית וכך זה היה אצלי גם עד סקר הקוד הקודם עם נדב. הוא רצה בסקר קוד הקודם שההדפסה של קרב ביבשת מסוימת תבוא מיד אחרי ההדפסה של היבשת באופן מסודר ומובן ולא כמו שמופיע בפלט התרגיל. זו הדרך להבטיח שההדפסה של קרבות ביבשת תבוא מיד לאחר ההדפסה של היבשת ולא באופן "רנדומלי" שנובע מהאסינכרוניות כאשר הקרבות בין אורגניזמים באותה יבשת מטופלים ביבשות עצמן.

2020-03-18 22:47 UTC, orcohen5 commented on src/main/java/Utilities/ExecutorServiceUtil.java
> +    private static ScheduledExecutorService startExecutor = Executors.newSingleThreadScheduledExecutor();
כפי שדיברנו בסקר החי השימוש בו נעשה במחלקת EvolutionManager לשם הפעלת מחזור החיים של הכוכב כל שנייה.

2020-03-18 22:49 UTC, orcohen5 commented on src/main/java/Places/Continent.java
>              executor.execute(organisms.get(i));
צורת הfor תשונה מfor i לfor each

2020-03-19 15:51 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +            LoggerUtil.logData(continentData + fightData);
זו לא הדרך לבצע את זה.

לכל משתנה בקוד שלך אמור להיות תפקיד מוגדר. תפקיד המשתנה fightData הוא להחזיק את המידע להדפסה של הקרב.
ברגע שהשתמשת בו כך, הוספת לו עוד תפקיד די כבד: להיות אחראי לחלוק ההדפסות של היבשת

שים לב שהקרבות שלך הם ת'רדים, ות'רדים אפשר לנהל (מתי הם מתחילים, לוודא שהם נגמרו לפני שממשיכים הלאה...) באמצעות כלים של הספרייה שהבאת של executorService

2020-03-19 15:51 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +            LoggerUtil.logData(continentData + fightData);
זו לא הדרך לבצע את זה.

לכל משתנה בקוד שלך אמור להיות תפקיד מוגדר. תפקיד המשתנה fightData הוא להחזיק את המידע להדפסה של הקרב.
ברגע שהשתמשת בו כך, הוספת לו עוד תפקיד די כבד: להיות אחראי לחלוק ההדפסות של היבשת

שים לב שהקרבות שלך הם ת'רדים, ות'רדים אפשר לנהל (מתי הם מתחילים, לוודא שהם נגמרו לפני שממשיכים הלאה...) באמצעות כלים של הספרייה שהבאת של executorService

2020-03-19 15:52 UTC, talrubin1123 commented on src/main/java/Utilities/ExecutorServiceUtil.java
> +    private static ScheduledExecutorService startExecutor = Executors.newSingleThreadScheduledExecutor();
הייתי משנה את השם למשהו כמו executorScheduler

2020-03-19 15:53 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +            LoggerUtil.logData(continentData + fightData);
זו לא הדרך לבצע את זה.

לכל משתנה בקוד שלך אמור להיות תפקיד מוגדר. תפקיד המשתנה fightData הוא להחזיק את המידע להדפסה של הקרב.
ברגע שהשתמשת בו כך, הוספת לו עוד תפקיד די כבד: להיות אחראי לחלוק ההדפסות של היבשת

שים לב שהקרבות שלך הם ת'רדים, ות'רדים אפשר לנהל (מתי הם מתחילים, לוודא שהם נגמרו לפני שממשיכים הלאה...) באמצעות כלים של הספרייה שהבאת של executorService

2020-03-19 15:55 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +            Thread.sleep(1000);
זו לא הדרך לבצע זאת,
שים לב שסבבי החיים שלך הם ת'רדים, ות'רדים אפשר לנהל (מתי הם מתחילים, לוודא שהם נגמרו לפני שממשיכים הלאה...) באמצעות כלים של הספרייה שהבאת של executorService

2020-03-20 15:20 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +    private void announceFight(Organism attacker, Organism defender) {
המידע לא נכתב פעמיים. הפונקציה announceFight מוסיפה להדפסה מי נלחם במי ושתי הפונקציות האחרות מוסיפות לאותה ההדפסה את תוצאות הקרב - במקרה של תיקו ובמקרה של ניצחון של אחד האורגניזמים. אפשר לעשות את זה בפונקציות נפרדות כמו שאני ראיתי לנכון ואפשר גם בפונקציה אחת עם if-ים במקרה של תיקו וניצחון. לא בעייתי לשנות את זה למה שיותר מקובל מבחינתך.

2020-03-20 15:26 UTC, talrubin1123 commented on src/main/java/Places/Continent.java
> +    private void announceFight(Organism attacker, Organism defender) {
אבל אתה מדפיס לי את זה בשני לוגים נפרדים. זה לא עונה על הדרישה. מבקשת שתלך לסוף התרגיל לדוגמאות הדפסה ותראה איך מודפס קרב ב lifecycle

2020-03-22 00:49 UTC, orcohen5 commented on src/main/java/Utilities/ExecutorServiceUtil.java
> +    private static final int THREADS_NUMBER = 5;
בהתאם למספר היבשות בתרגיל והוספתי עוד 1 כדי שלא יהיה חוסר במשאבים.

2020-03-22 00:49 UTC, orcohen5 commented on src/main/java/Utilities/ExecutorServiceUtil.java
> +    private static ScheduledExecutorService startExecutor = Executors.newSingleThreadScheduledExecutor();
שיניתי

2020-03-22 00:51 UTC, orcohen5 commented on src/main/java/Events/EvolutionManager.java
> +    private List<Organism> americanOrganismsList;
כולם הפכו להיות משתנים לוקאליים פרט ל-executor כפי שדיברנו.

2020-03-22 00:51 UTC, orcohen5 commented on src/main/java/Events/EvolutionManager.java
>          planet = Planet.getInstance(continentsList);
טופל. הוספת היבשות נעשית בנפרד מאתחול הכוכב.

2020-03-22 00:53 UTC, orcohen5 commented on src/main/java/Events/EvolutionManager.java
לאחר חיפושים רבים מצאתי דוגמה לחלוקה ל-packages והלכתי לפיה.
שיניתי בהתאם את כל ה-packages ואת חלוקת הקבצים בתוכם.

2020-03-22 00:54 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +            Thread.sleep(1000);
מנגנון הסנכרון השתנה כך שאין צורך במתן שנייה לסידור ההעלאות.

2020-03-22 00:54 UTC, orcohen5 commented on src/main/java/Places/Continent.java
>              executor.execute(organisms.get(i));
שונתה

2020-03-22 00:55 UTC, orcohen5 commented on src/main/java/Places/Continent.java
>          startOrganismsFight();
טופל

2020-03-22 00:56 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +            LoggerUtil.logData(continentData + fightData);
הדפסת הקרבות מתבצעת כעת בנפרד מהדפסת היבשות.
הקרבות ממומשים באורגניזם עצמו ומודפסים גם שם.

2020-03-22 00:56 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +        List<Organism> attackersToRemove = new ArrayList();
נמחקו

2020-03-22 00:56 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +                        attacker.setOrganismAlive(false);
נמחק

2020-03-22 00:57 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +                        announceDraw(attacker, defender);
טופל. כעת ישנה הבחנה בין מצבים של תיקו, מגן מנצח ותוקף מנצח.

2020-03-22 00:57 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +                    else {
שונה בכל הפרויקט.

2020-03-22 00:57 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +                    currentAttackers.remove(attacker);
נמחקו

2020-03-22 00:58 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +                areAttackerAndDefenderHavePeople(attacker, defender);
נמחקו

2020-03-22 01:00 UTC, orcohen5 commented on src/main/java/Places/Continent.java
מימוש הסנכרון השתנה. בתוך פונקציית attack באורגניזם יש שני בלוקים של synchronized אחד בתוך השני - אחד לתוקף ואחד למגן, כפי שדיברנו בסקר החי.

2020-03-22 01:00 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +    private final int DIFFERENCE = 5;
שונה לDIFFERENCE_BETWEEN_PROPERTIES והועבר למחלקת Organism ביחד עם הקרבות.

2020-03-22 01:01 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +    private final int MINIMUM_BALANCE = 1;
נמחק

2020-03-22 01:01 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +                    defender.setOrganismAlive(false);
נמחק

2020-03-22 01:03 UTC, orcohen5 commented on src/main/java/Places/Continent.java
> +    private void announceFight(Organism attacker, Organism defender) {
ההדפסה כבר הייתה בלוג אחד ויחיד גם קודם וגם עכשיו.
ההרכבה של String המכיל את נתוני הקרב נעשית בפונקציות שונות לשם קריאות טובה יותר.
הדפסת הקרבות השתנתה לאחר שמימוש הקרבות הועבר למחלקת Organism.

2020-03-22 01:04 UTC, orcohen5 commented on src/main/java/Places/Planet.java
>      public static Planet getInstance(List<Continent> continents) {
שונה בכל הפרויקט.

2020-03-22 01:04 UTC, orcohen5 commented on src/main/java/Places/Planet.java
> +    private synchronized void startLifeCycle() {
לא.
טופל

2020-03-22 01:05 UTC, orcohen5 commented on src/main/java/Places/Planet.java
> +            LoggerUtil.logData("______________");
ההדפסה נעשית בסוף כל סבב במחלקת הPlanet לאחר שכל היבשות ביצעו מחזור חיים אחד.

2020-03-22 01:19 UTC, orcohen5 commented
בוקר טוב!
כפי שדיברנו,
מימוש מנגנון הסנכרון והת'רדים השתנה לפי מה שדיברנו בסקר החי.
מימוש הקרבות עבר למחלקת Organism בפונקציית attack ומעט פונקציות נלוות האחראיות על הדפסת נתוני הקרב שמתבצעת גם בלוג אחד ויחיד במחלקת Organism.
לאחר חיפושים רבים מצאתי דוגמה לחלוקה של packages בפרויקט והתאמתי את הפרויקט לפיה (מקווה שתאהבי).
נדבר :)

2020-03-22 10:52 UTC, talrubin1123 commented on src/main/java/Places/Planet.java
>      public static Planet getInstance(List<Continent> continents) {
אש

2020-03-24 12:43 UTC, talrubin1123 requested changes

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Continent.java
> +        Future<?> task;
מה זה? למה זה משמש? תקרא באינטרנט ותסביר לי @orcohen5

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Continent.java
> +        Future<?> task;
אולי כדאי שם קריא יותר?

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Continent.java
> +        this.organisms = organisms;
הייתי עושה קונסטרקטור נוסף שלא מחייב אותי לשלוח לו רשימה של אורגניזמים אלא מאתחל את הרשימה בעצמו ללא אורגניזמים, על מנת לאפשר גמישות עם המשתמש. 
שמעת פעם על overloading?

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Continent.java
> +    public List<Organism> getOrganisms() {
שמות ה getters & setters צריכים להיות כשמות המשתנים אותם מחזירים 
(בנוסף לפקודת ה get) 
בנוסף, אני אשמח לשמות יותר משמעותיים למשתנים עצמם- כמו continentName, OrganismsInContinent

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Continent.java
> +        for (Organism organism: organisms) {
חסר תו רווח לפני הנקודותיים

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Continent.java
> +            while (task.isDone() == false) {
צורת העבודה פה היא לא נכונה.
תוכל להסביר לי מדוע?

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Continent.java
> +                    result = attacker.attack(defender);
שם יותר מפורט

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Continent.java
> +        return attacker.getSumOfProperties() - defender.getSumOfProperties() > DIFFERENCE_BETWEEN_PROPERTIES &&
לתחום בסוגריים את הביטויים הלוגיים למען קריאות

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Planet.java
> +    private static Planet instance = null;
מיותר לאתחל ב null

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Planet.java
> +    private static Planet instance = null;
תסביר לי למה

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Planet.java
> +    private List<Continent> continents;
שם יותר מפורט

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Planet.java
> +    private ExecutorService executor;
שם יותר ספציפי

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/Planet.java
> +        notifyStart();
תחשוב איפה המקום הנכון לבצע את זה

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/organisms/Organism.java
> +    public void run() {
מה תפקיד המתודה?
האם תפקידה לנהל את כל הפונקציות האלה עם הלוגיקה הזו?

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/organisms/Organism.java
> +                StringBuilder builder = new StringBuilder();
שם יותר מהותי ומשמעותי. תפרט בשם

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/organisms/Organism.java
> +                addResultToFightAnnouncement(defender, result, builder);
חסרה לך שורת רווח לאחר סגירת בלוק

2020-03-24 12:43 UTC, talrubin1123 commented on src/main/java/evolution/entities/organisms/Organism.java
> +    private void addResultToFightAnnouncement(Organism defender, int result, StringBuilder builder) {
אתה לא חושב שזו מתודה מיותרת ויכלת לעשות את זה במתודה של הקרב עצמו?

2020-03-24 13:52 UTC, orcohen5 commented on src/main/java/evolution/entities/Continent.java
> +        this.organisms = organisms;
נוסף קונסטרקטור כפי שביקשת

2020-03-24 13:56 UTC, orcohen5 commented on src/main/java/evolution/entities/Continent.java
> +    public List<Organism> getOrganisms() {
אלו היו שמות המשתנים אצלי עד תחילת חלק ג אך הם קוצרו לבקשת נדב (לדעתו הם היו ארוכים מדי ומובנים מאליו) וכעת חזרו לשמם המקורי.
ה-getters וה-setters היו ועדיין תואמים לשמות המשתנים.

2020-03-24 13:56 UTC, orcohen5 commented on src/main/java/evolution/entities/Continent.java
> +        for (Organism organism: organisms) {
נוסף רווח

2020-03-24 13:57 UTC, orcohen5 commented on src/main/java/evolution/entities/Continent.java
> +                    result = attacker.attack(defender);
שונה ל-fightResult

2020-03-24 13:57 UTC, orcohen5 commented on src/main/java/evolution/entities/Continent.java
> +        return attacker.getSumOfProperties() - defender.getSumOfProperties() > DIFFERENCE_BETWEEN_PROPERTIES &&
נוספו סוגריים

2020-03-24 14:01 UTC, orcohen5 commented on src/main/java/evolution/entities/Planet.java
> +    private static Planet instance = null;
ראיתי את זה בהרבה דוגמאות למימוש singleton ולכן עשיתי כך כאן אבל הורדתי את זה עכשיו.
כאשר יש משתנה סטטי שלא מאותחל או מאותחל ל-null, בזמן קומפילציה המשתנה מאותחל אוטומטית לפי הקונסטרקטור הדיפולטי של מחלקת המשתנה. בקוד מופיע אחד כזה ולכן האתחול של המשתנה ל-null מיותר.

2020-03-24 14:01 UTC, orcohen5 commented on src/main/java/evolution/entities/Planet.java
> +    private List<Continent> continents;
שונה לשם המקורי שהיה בתחילת חלק ג - continentsInPlanet

2020-03-24 14:02 UTC, orcohen5 commented on src/main/java/evolution/entities/Planet.java
> +    private ExecutorService executor;
שונה ל-planetExecutor.

2020-03-24 14:03 UTC, orcohen5 commented on src/main/java/evolution/entities/Planet.java
> +        notifyStart();
הועבר לתחילת ביצוע מחזור החיים (StartLifeCycle).

2020-03-24 14:03 UTC, orcohen5 commented on src/main/java/evolution/entities/organisms/Organism.java
> +                StringBuilder builder = new StringBuilder();
שונה ל-fightDataBuilder

2020-03-24 14:04 UTC, orcohen5 commented on src/main/java/evolution/entities/organisms/Organism.java
> +                addResultToFightAnnouncement(defender, result, builder);
נוספה שורת רווח

2020-03-24 14:05 UTC, orcohen5 commented on src/main/java/evolution/entities/organisms/Organism.java
> +    private void addResultToFightAnnouncement(Organism defender, int result, StringBuilder builder) {
חשבתי שזה יותר יפה מבחינת clean code להוציא את זה למתודה נפרדת.
החזרתי את תוכן המתודה לתוך מתודת הקרב.

2020-03-24 14:06 UTC, orcohen5 commented on src/main/java/evolution/entities/organisms/Organism.java
> +    public void run() {
תפקיד המתודה הוא לבצע את החלק של מחזור החיים שמתבצע באורגניזם.
לכן נוספה מתודה startLifeCycle גם באורגניזם בהתאם למה שמופיע ביבשת וכוכב.

2020-03-24 14:09 UTC, talrubin1123 requested changes

2020-03-24 14:09 UTC, talrubin1123 commented on src/main/java/evolution/entities/Planet.java
> +        notifyStart();
תחשוב שוב.

2020-03-24 14:14 UTC, orcohen5 commented on src/main/java/evolution/entities/Continent.java
> +        Future<?> task;
שונה ל-organismTaskResult (משום שהוא מקבל את תוצאת המשימה של ביצוע הגדלת נתוני האורגניזם לפי מחזור החיים).
האובייקט מייצג תוצאה של חישוב אסינכרוני. כאשר המשימה האסינכרונית נוצרת, מוחזר אובייקט מסוג Future המטפל בתוצאת המשימה האסינכרונית. כאשר האובייקט מסתיים, ניתן לגשת לתוצאת המשימה דרך האובייקט.
השתמשתי בזה כאן בעיקר כדי לדעת שהמשימה אכן הסתיימה ובמידת הצורך לתת לה זמן מועט נוסף לסיום המשימה כדי שההגדלות יהיו מתואמות בין כל הת'רדים במחזור החיים - כפי שראיתי במספר דוגמאות למימוש מנגנון הסנכרון.

2020-03-24 14:19 UTC, orcohen5 commented on src/main/java/evolution/entities/Continent.java
> +            while (task.isDone() == false) {
מימשתי את זה לפי מספר דוגמאות שראיתי למימוש מנגנון סנכרון הת'רדים. שיניתי את ה-while ל-if משום שלא צריך לתת יותר מדי זמן למשימה כדי שתסתיים. מספיק שתהיה תוספת זמן אחת קטנה מאוד כדי שהמשימה תסתיים ולכן זה יותר נכון לוגית. הורדתי גם את ה-false והחלפתי אותו בסימן קריאה ! בתחילת התנאי כדי לקבל תנאי קצר יותר ונכון יותר.

2020-03-24 14:21 UTC, orcohen5 commented on src/main/java/evolution/entities/Planet.java
> +        notifyStart();
בחלק של ה-initilaize ב-EvolutionManager?

2020-03-24 14:24 UTC, orcohen5 commented on src/main/java/evolution/entities/Planet.java
> +        notifyStart();
ב-startEvolution ב-EvolutionManager?

2020-03-24 14:44 UTC, orcohen5 commented on src/main/java/evolution/entities/Planet.java
> +        notifyStart();
הועבר ל-startEvolution. שם מתבצעת התחלת האבולוציה וזה מתאים שההודעה על ההתחלה תהיה שם. @talrubin1123

2020-03-24 14:58 UTC, talrubin1123 commented on src/main/java/evolution/entities/Planet.java
> +        notifyStart();
טוב מאוד

2020-03-24 14:58 UTC, talrubin1123 commented on src/main/java/evolution/entities/organisms/Organism.java
> +                StringBuilder builder = new StringBuilder();
לא צריך את המילה builder

2020-03-24 15:02 UTC, orcohen5 commented on src/main/java/evolution/entities/organisms/Organism.java
> +                StringBuilder builder = new StringBuilder();
מחקתי את המילה builder מהשם.

2020-03-24 15:10 UTC, merged